/**
 * Valid synthetic examples, one or more per contract.
 *
 * Every value here is invented. No real member, no real phone number, no real
 * place. The Miami neighbourhoods are real neighbourhoods and nothing else in
 * these fixtures corresponds to a person.
 *
 * `test/examples.test.ts` parses every one of these against its contract, and
 * `test/json-schema-agreement.test.ts` also runs them through an independent
 * JSON Schema implementation. An example that stops being valid is a contract
 * change that nobody wrote down.
 */

export interface ValidExample {
  readonly id: string;
  readonly contract: string;
  /** What this example is demonstrating. */
  readonly note: string;
  readonly value: unknown;
}

const MEMBER = 'member:m_0001';
const NOW = '2026-08-04T18:00:00Z';

// --- shared statement fixtures --------------------------------------------

export const knownFromCalendar = {
  statement_id: 'stmt:s_known_1',
  kind: 'known',
  text: 'You are booked until 2pm, then clear until 6.',
  source: { type: 'calendar_freebusy', ref: 'projection:p_0001' },
  observed_at: NOW,
};

export const userReported = {
  statement_id: 'stmt:s_reported_1',
  kind: 'user_reported',
  text: 'You said you swam once this week.',
  source: { type: 'member_sms', ref: 'request:r_0001' },
  reported_at: '2026-08-03T22:10:00Z',
  verified: false,
};

export const inferredWindow = {
  statement_id: 'stmt:s_inferred_1',
  kind: 'inferred',
  text: 'Thursday afternoons are usually open for you.',
  source: { type: 'heuristic', ref: 'rule:stated_windows_v1' },
  hedge: 'usually',
  confidence: 'medium',
  basis: ['profile:pr_0001'],
  inferred_at: NOW,
};

export const proposedAction = {
  statement_id: 'stmt:s_action_1',
  kind: 'proposed_action',
  text: 'Swim at the pool ten minutes from Brickell at 4pm.',
  window: { starts_at: '2026-08-06T20:00:00Z', ends_at: '2026-08-06T21:00:00Z' },
  goal_ref: 'goal:g_swim',
  place_ref: 'place:pl_pool_1',
  urgency: 'none',
};

// --- the examples ----------------------------------------------------------

export const VALID_EXAMPLES: readonly ValidExample[] = [
  {
    id: 'statement.known',
    contract: 'cedrus.statement',
    note: 'A known statement citing the free/busy projection it was read from.',
    value: knownFromCalendar,
  },
  {
    id: 'statement.inferred',
    contract: 'cedrus.statement',
    note: 'An inference, hedged in the text and in a field, resting on at least one basis.',
    value: inferredWindow,
  },
  {
    id: 'statement.user_reported',
    contract: 'cedrus.statement',
    note: 'A self-report. Unverified, and structurally unable to claim otherwise.',
    value: userReported,
  },
  {
    id: 'statement.proposed_action',
    contract: 'cedrus.statement',
    note: 'One action, sized to a window, hung on a goal, with no manufactured urgency.',
    value: proposedAction,
  },

  {
    id: 'member_profile.minimal',
    contract: 'cedrus.member_profile',
    note: 'The founding-release minimum: a name and a phone. Everything else is genuinely absent, not defaulted.',
    value: {
      schema_version: 2,
      member_id: MEMBER,
      display_name: 'Test Member One',
      name_source: 'member_entered',
      phone: '17865550101',
      phone_verified_at: null,
      timezone: 'America/New_York',
      open_to_introductions: false,
      recommendable: false,
      onboarding_completed_steps: ['name'],
      onboarding_completed_at: null,
      created_at: '2026-08-01T14:00:00Z',
      updated_at: NOW,
    },
  },
  {
    id: 'member_profile.onboarded',
    contract: 'cedrus.member_profile',
    note: 'A member who finished onboarding, including stated free windows, which is what makes Today work before Calendar.',
    value: {
      schema_version: 2,
      member_id: MEMBER,
      display_name: 'Test Member One',
      name_source: 'member_entered',
      phone: '17865550101',
      phone_verified_at: '2026-08-01T14:20:00Z',
      email: 'member-one@example.invalid',
      timezone: 'America/New_York',
      work_setup: 'fully_remote',
      neighborhood: 'brickell',
      stated_free_windows: [
        { weekday: 'thursday', starts_at_local: '14:00', ends_at_local: '18:00' },
        { weekday: 'friday', starts_at_local: '09:00', ends_at_local: '12:00' },
      ],
      activities: ['swimming', 'shipping my own thing'],
      current_groups: [],
      open_to_introductions: true,
      recommendable: true,
      onboarding_completed_steps: [
        'name',
        'work_setup',
        'neighborhood',
        'free_windows',
        'activities',
        'current_groups',
        'people',
        'social_prefs',
      ],
      onboarding_completed_at: '2026-08-01T14:25:00Z',
      created_at: '2026-08-01T14:00:00Z',
      updated_at: NOW,
    },
  },

  {
    id: 'goal.with_lane',
    contract: 'cedrus.goal',
    note: "A goal in the member's own words, sorted into a lane, with cadence stored as text rather than parsed.",
    value: {
      schema_version: 2,
      goal_id: 'goal:g_swim',
      member_id: MEMBER,
      stated_text: 'swim twice a week',
      lane: 'body',
      cadence_text: 'a couple of times a week',
      origin: 'user_set',
      status: 'open',
      priority: 1,
      created_at: '2026-08-01T14:30:00Z',
      updated_at: NOW,
    },
  },
  {
    id: 'goal.unsorted',
    contract: 'cedrus.goal',
    note: 'A goal we could not sort. The lane is null rather than guessed.',
    value: {
      schema_version: 2,
      goal_id: 'goal:g_ship',
      member_id: MEMBER,
      stated_text: 'ship the thing I keep not shipping',
      lane: null,
      origin: 'user_set',
      status: 'open',
      priority: null,
      created_at: '2026-08-01T14:31:00Z',
      updated_at: NOW,
    },
  },
  {
    id: 'goal_set.empty',
    contract: 'cedrus.goal_set',
    note: 'Zero goals is a valid state. A member who has not answered yet is not an error.',
    value: {
      schema_version: 2,
      member_id: MEMBER,
      goals: [],
      one_is_enough_shown: true,
      updated_at: NOW,
    },
  },

  {
    id: 'voice_preference.preset',
    contract: 'cedrus.voice_preference',
    note: 'The week-two implementation: three presets. Safety registers are outside what the field can address.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      mode: 'preset',
      preset: 'direct',
      applies_to: ['assistant_replies', 'pace_cards'],
      safety_register_fixed: true,
      updated_at: NOW,
    },
  },
  {
    id: 'voice_preference.free_form',
    contract: 'cedrus.voice_preference',
    note: 'The destination: the member says how to talk to them, in their own words.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      mode: 'free_form',
      instruction_text: 'short sentences, no exclamation marks, tell me the thing first',
      applies_to: ['assistant_replies'],
      safety_register_fixed: true,
      updated_at: NOW,
    },
  },

  {
    id: 'consent_event.sms',
    contract: 'cedrus.consent_event',
    note: 'A2P compliant: affirmative, separate, unchecked by default, with the exact wording stored.',
    value: {
      schema_version: 1,
      consent_id: 'consent:c_0001',
      member_id: MEMBER,
      contact_ref: 'contact:ct_0001',
      channel: 'sms_assistant',
      granted: true,
      exact_wording:
        'Text me about Cedrus access and requests I send to the Cedrus assistant. Message frequency varies. Message and data rates may apply. Reply STOP to opt out, HELP for help. See Terms and Privacy.',
      bundled: false,
      preselected: false,
      occurred_at: '2026-08-01T13:59:00Z',
      ip_address: '203.0.113.10',
      superseded_by: null,
    },
  },
  {
    id: 'permission_state.suppressed',
    contract: 'cedrus.permission_state',
    note: 'Suppression is permanent and separate from permission. A hard bounce is never retried.',
    value: {
      schema_version: 1,
      contact_ref: 'contact:ct_0002',
      email_marketing: false,
      sms_assistant: true,
      suppressed: true,
      suppression_reason: 'hard_bounce',
      derived_from_consent_ids: 'consent:c_0002',
      computed_at: NOW,
    },
  },

  {
    id: 'connection_authorization.google_freebusy',
    contract: 'cedrus.connection_authorization',
    note: 'One narrow purpose, one named outcome, one scope, and the whole pre-consent disclosure recorded.',
    value: {
      schema_version: 2,
      connection_id: 'conn:cn_0001',
      member_id: MEMBER,
      provider: 'google_calendar',
      scopes: ['calendar.freebusy.read'],
      purpose: {
        code: 'place_suggestions_in_open_time',
        statement: 'Place suggestions in time that is actually open on your calendar.',
      },
      named_outcome: {
        code: 'suggestions_land_in_time_you_actually_have',
        statement: 'Suggestions land in time you actually have, instead of on top of a meeting.',
      },
      disclosure: {
        reads: 'When you are busy and when you are free.',
        does_not_read: 'Event names, descriptions, locations, guests, or anything in Gmail.',
        will_do: 'Place suggestions in time that is actually open.',
        does_not_do: 'Cedrus does not create or change events.',
      },
      consent_ref: 'consent:c_0003',
      status: 'authorized',
      authorized_at: '2026-08-04T15:00:00Z',
      last_sync_at: NOW,
      revoked_at: null,
      token_storage: 'server_only',
      revocable: true,
      writes_to_provider: false,
      state_validated: true,
    },
  },

  {
    id: 'calendar_projection.live',
    contract: 'cedrus.calendar_freebusy_projection',
    note: 'Busy intervals and nothing else. There is no field on this shape that could hold a title.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      connection_ref: 'conn:cn_0001',
      provider: 'google_calendar',
      window: { starts_at: '2026-08-04T04:00:00Z', ends_at: '2026-08-07T04:00:00Z' },
      busy: [
        { starts_at: '2026-08-04T13:00:00Z', ends_at: '2026-08-04T18:00:00Z' },
        { starts_at: '2026-08-05T15:00:00Z', ends_at: '2026-08-05T16:00:00Z' },
      ],
      freshness: 'live',
      synced_at: NOW,
    },
  },
  {
    id: 'calendar_projection.disconnected',
    contract: 'cedrus.calendar_freebusy_projection',
    note: 'A projection that never ran. Distinguishable from an empty live one, which is Lesson 7.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      connection_ref: null,
      provider: 'google_calendar',
      window: { starts_at: '2026-08-04T04:00:00Z', ends_at: '2026-08-07T04:00:00Z' },
      busy: [],
      freshness: 'disconnected',
      synced_at: null,
    },
  },
  {
    id: 'availability.stated',
    contract: 'cedrus.availability',
    note: 'Availability from stated windows, carrying the notice that says which one it is.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      date: '2026-08-06T04:00:00Z',
      basis: 'stated',
      open_windows: [{ starts_at: '2026-08-06T18:00:00Z', ends_at: '2026-08-06T22:00:00Z' }],
      fallback_notice: 'using_your_usual_windows',
      computed_at: NOW,
    },
  },
  {
    id: 'availability.calendar',
    contract: 'cedrus.availability',
    note: 'Availability from a live projection. No fallback notice, because there was no fallback.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      date: '2026-08-04T04:00:00Z',
      basis: 'calendar',
      open_windows: [{ starts_at: '2026-08-04T18:00:00Z', ends_at: '2026-08-04T22:00:00Z' }],
      fallback_notice: null,
      computed_at: NOW,
    },
  },

  {
    id: 'pace_card.delivered',
    contract: 'cedrus.pace_card',
    note: 'The four blocks, each tagged, one proposed action, reviewed before delivery.',
    value: {
      schema_version: 1,
      card_id: 'card:cd_0001',
      member_id: MEMBER,
      goal_ref: 'goal:g_swim',
      for_date: '2026-08-06',
      parts: [knownFromCalendar, userReported, inferredWindow, proposedAction],
      window: { starts_at: '2026-08-06T20:00:00Z', ends_at: '2026-08-06T21:00:00Z' },
      status: 'delivered',
      review_ref: 'review:rv_0001',
      created_at: '2026-08-06T12:00:00Z',
      delivered_at: '2026-08-06T13:00:00Z',
      delivered_via: 'sms',
      voice_ref: 'voice:v_0001',
    },
  },

  {
    id: 'card_outcome.did_not',
    contract: 'cedrus.card_outcome',
    note: '"I didn\'t" is a first-class answer, exactly as easy to record as "I did".',
    value: {
      schema_version: 2,
      outcome_id: 'outcome:o_0001',
      card_id: 'card:cd_0001',
      member_id: MEMBER,
      outcome: 'did_not',
      helped: null,
      rejection_reason: null,
      rejection_scope: null,
      source: 'tap',
      verified: false,
      recorded_at: '2026-08-06T23:00:00Z',
    },
  },
  {
    id: 'card_outcome.silent',
    contract: 'cedrus.card_outcome',
    note: 'Silence recorded explicitly rather than inferred from absence.',
    value: {
      schema_version: 2,
      outcome_id: 'outcome:o_0002',
      card_id: 'card:cd_0002',
      member_id: MEMBER,
      outcome: 'silent',
      helped: null,
      rejection_reason: null,
      rejection_scope: null,
      source: 'no_response',
      verified: false,
      recorded_at: '2026-08-07T12:00:00Z',
    },
  },
  {
    id: 'member_activity.typed',
    contract: 'cedrus.member_activity',
    note: 'Fitness and activity are typed in, not integrated. There is no provider field on this shape.',
    value: {
      schema_version: 1,
      activity_id: 'activity:a_0001',
      member_id: MEMBER,
      goal_ref: 'goal:g_swim',
      text: 'swam this morning before the first call',
      happened_at: '2026-08-04T12:00:00Z',
      source: 'sms',
      entry_method: 'typed',
      verified: false,
      recorded_at: '2026-08-04T12:05:00Z',
    },
  },

  {
    id: 'place.curated',
    contract: 'cedrus.place',
    note: 'Operator-curated. A scraped row cannot satisfy this contract.',
    value: {
      schema_version: 1,
      place_id: 'place:pl_pool_1',
      name: 'Test Pool (synthetic fixture)',
      neighborhood: 'brickell',
      origin: 'operator_curated',
      suitable_for: ['either'],
      typical_hours: [{ weekday: 'thursday', opens_at_local: '06:00', closes_at_local: '20:00' }],
      operator_note: 'Quiet at 4 on a weekday.',
      curated_at: '2026-08-02T16:00:00Z',
    },
  },
  {
    id: 'place_suggestion.attached_to_window',
    contract: 'cedrus.place_suggestion',
    note: 'A place surfaces only attached to a window. The window is required, not optional.',
    value: {
      schema_version: 1,
      place_ref: 'place:pl_pool_1',
      member_id: MEMBER,
      window: { starts_at: '2026-08-06T20:00:00Z', ends_at: '2026-08-06T21:00:00Z' },
      rationale_statement_ref: 'stmt:s_inferred_1',
    },
  },
  {
    id: 'person.member_stated',
    contract: 'cedrus.person',
    note: 'Someone the member mentioned. No introductions in the founding release, and no contact details anywhere.',
    value: {
      schema_version: 1,
      person_id: 'person:pn_0001',
      member_id: MEMBER,
      display_name: 'Ana',
      origin: 'member_stated',
      relationship_text: 'friend I keep meaning to see',
      introduction_state: 'none',
      introduction_consent_refs: [],
      last_mentioned_at: '2026-08-02T19:00:00Z',
      created_at: '2026-08-01T14:40:00Z',
    },
  },
  {
    id: 'plan.one_action',
    contract: 'cedrus.plan',
    note: 'One action, sized to a window. The shape holds a single action ref, not a list.',
    value: {
      schema_version: 1,
      plan_id: 'plan:p_0001',
      member_id: MEMBER,
      goal_ref: 'goal:g_swim',
      kind: 'suggestion',
      action_statement_ref: 'stmt:s_action_1',
      window: { starts_at: '2026-08-06T20:00:00Z', ends_at: '2026-08-06T21:00:00Z' },
      place_ref: 'place:pl_pool_1',
      person_refs: [],
      created_at: '2026-08-06T12:00:00Z',
    },
  },
  {
    id: 'progression.nothing_moved',
    contract: 'cedrus.progression',
    note: 'The honest week. Allowed to say nothing moved, and the counts agree with it.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      window: { starts_at: '2026-07-28T04:00:00Z', ends_at: '2026-08-04T04:00:00Z' },
      lines: [
        {
          goal_ref: 'goal:g_swim',
          goal_stated_text: 'swim twice a week',
          lane: 'body',
          cards_suggested: { value: 1, basis: 'observed_rows', source_refs: ['card:cd_0002'] },
          outcomes_recorded: { value: 0, basis: 'observed_rows', source_refs: [] },
          confirmed_helped: { value: 0, basis: 'observed_rows', source_refs: [] },
          summary_text: 'Nothing moved on this one last week.',
        },
      ],
      nothing_moved: true,
      computed_at: NOW,
    },
  },
  {
    id: 'progression.moved',
    contract: 'cedrus.progression',
    note: 'Every number names the records it counted. Three would mean three rows.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      window: { starts_at: '2026-07-28T04:00:00Z', ends_at: '2026-08-04T04:00:00Z' },
      lines: [
        {
          goal_ref: 'goal:g_swim',
          goal_stated_text: 'swim twice a week',
          lane: 'body',
          cards_suggested: { value: 2, basis: 'observed_rows', source_refs: ['card:cd_0001', 'card:cd_0002'] },
          outcomes_recorded: { value: 2, basis: 'observed_rows', source_refs: ['outcome:o_0001', 'outcome:o_0003'] },
          confirmed_helped: { value: 1, basis: 'observed_rows', source_refs: ['outcome:o_0003'] },
          summary_text: 'You swam once and skipped once.',
        },
      ],
      nothing_moved: false,
      computed_at: NOW,
    },
  },

  {
    id: 'today.before_calendar',
    contract: 'cedrus.today_state',
    note: 'Today before Calendar. The day line is an inference and says so, and the fallback is announced.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      for_date: '2026-08-06',
      timing_basis: 'stated',
      day_line: inferredWindow,
      fallback_notice: 'using_your_usual_windows',
      card: null,
      goals: [
        {
          goal_ref: 'goal:g_swim',
          stated_text: 'swim twice a week',
          status_statement: userReported,
          can_report_outcome: true,
        },
      ],
      empty_state: null,
      sms_handoff: { cedrus_number: '17865550100', prefilled_text: 'Cedrus, ' },
      computed_at: NOW,
    },
  },
  {
    id: 'today.empty_state',
    contract: 'cedrus.today_state',
    note: 'Week one. Honest, specific, and structurally unable to show an example card.',
    value: {
      schema_version: 1,
      member_id: MEMBER,
      for_date: '2026-08-05',
      timing_basis: 'stated',
      day_line: inferredWindow,
      fallback_notice: 'using_your_usual_windows',
      card: null,
      goals: [],
      empty_state: {
        known_so_far: ['You work from Brickell.', 'Thursday afternoons are usually open.'],
        waiting_for: ['One thing you want more of.'],
        shows_example_card: false,
      },
      sms_handoff: { cedrus_number: '17865550100' },
      computed_at: NOW,
    },
  },

  {
    id: 'operator_review.killed_with_reason',
    contract: 'cedrus.operator_review',
    note: 'Every kill is logged with a reason. That log is the training signal.',
    value: {
      schema_version: 1,
      review_id: 'review:rv_0002',
      card_ref: 'card:cd_0003',
      member_ref: MEMBER,
      reviewer: 'operator',
      decision: 'killed',
      reason_code: 'overclaimed_certainty',
      reason_text: 'The card said "you are free" from stated windows, not from the calendar.',
      edited_statement_refs: [],
      reviewed_at: '2026-08-06T12:30:00Z',
      delivery_gated_on_review: true,
    },
  },
  {
    id: 'agent_request.out_of_scope',
    contract: 'cedrus.agent_request',
    note: 'Outside the narrow promise: honestly declined, logged, and not filed under a job it does not belong to.',
    value: {
      schema_version: 1,
      request_id: 'request:r_0002',
      member_id: MEMBER,
      channel: 'sms',
      text: 'can you book me a flight to Bogota next month',
      received_at: '2026-08-04T17:00:00Z',
      in_scope: false,
      scope_job: null,
      response_kind: 'honest_decline',
      logged_as_request: true,
      fixed_register_trigger: 'none',
      voice_applied: true,
    },
  },
  {
    id: 'agent_request.stop',
    contract: 'cedrus.agent_request',
    note: 'STOP stays in a fixed register regardless of the voice preference.',
    value: {
      schema_version: 1,
      request_id: 'request:r_0003',
      member_id: MEMBER,
      channel: 'sms',
      text: 'STOP',
      received_at: '2026-08-04T17:05:00Z',
      in_scope: false,
      scope_job: null,
      response_kind: 'safety_fixed_register',
      logged_as_request: true,
      fixed_register_trigger: 'stop',
      voice_applied: false,
    },
  },

  {
    id: 'analytics.card_outcome',
    contract: 'cedrus.analytics_event',
    note: 'Ids and enums. Nothing about what the card said or what the member wrote.',
    value: {
      schema_version: 1,
      event: 'card.outcome',
      event_id: 'event:ev_0001',
      member_id: MEMBER,
      occurred_at: '2026-08-06T23:00:00Z',
      props: { card_ref: 'card:cd_0001', outcome: 'did_not', source: 'tap' },
    },
  },
  {
    id: 'analytics.out_of_scope_request',
    contract: 'cedrus.analytics_event',
    note: 'The one deliberate exception: the out-of-scope request log carries the text, because that log is the roadmap.',
    value: {
      schema_version: 1,
      event: 'sms.request.out_of_scope',
      event_id: 'event:ev_0002',
      member_id: MEMBER,
      occurred_at: '2026-08-04T17:00:01Z',
      props: { request_ref: 'request:r_0002', request_text: 'can you book me a flight to Bogota next month' },
    },
  },
  {
    id: 'analytics.silent_window',
    contract: 'cedrus.analytics_event',
    note: 'A member who does nothing is a data point, not a gap.',
    value: {
      schema_version: 1,
      event: 'member.silent_window',
      event_id: 'event:ev_0003',
      member_id: MEMBER,
      occurred_at: '2026-08-11T12:00:00Z',
      props: { window_days: 7, observed_from: '2026-08-04T12:00:00Z' },
    },
  },

  {
    id: 'data_envelope.member_export',
    contract: 'cedrus.data_envelope',
    note: 'A member export whose count names every record it carries, with the withheld material disclosed.',
    value: {
      envelope_version: 1,
      kind: 'export',
      generated_at: NOW,
      member_id: MEMBER,
      source_system: 'cedrus_backend',
      records: [
        {
          contract: 'cedrus.goal',
          schema_version: 2,
          record_id: 'goal:g_swim',
          payload: { stated_text: 'swim twice a week', lane: 'body' },
        },
      ],
      integrity: {
        record_count: { value: 1, basis: 'observed_rows', source_refs: ['goal:g_swim'] },
        checksum_sha256: '0000000000000000000000000000000000000000000000000000000000000000',
      },
      redactions: [
        {
          contract: 'cedrus.connection_authorization',
          reason: 'credentials_never_exported',
          note: 'Tokens are server-side only and are not member data.',
        },
      ],
    },
  },

  {
    id: 'api_error.contract_violation',
    contract: 'cedrus.api_error',
    note: 'Names the contract, lists the issues, is not a 2xx, and carries no member content.',
    value: {
      schema_version: 1,
      http_status: 422,
      code: 'contract_violation',
      problem: 'cedrus.pace_card rejected the payload',
      contract: 'cedrus.pace_card',
      issues: [
        {
          path: 'parts[0].source.type',
          code: 'provenance/inference_as_known',
          explanation: 'a known statement may not cite model_inference',
        },
      ],
      retryable: false,
      retry_after_seconds: null,
      debug_ref: null,
      request_id: 'request:r_0004',
      occurred_at: NOW,
    },
  },
  {
    id: 'api_error.internal_with_debug_ref',
    contract: 'cedrus.api_error',
    note: 'An internal error still has to be traceable. Opaque errors cost hours.',
    value: {
      schema_version: 1,
      http_status: 500,
      code: 'internal_error',
      problem: 'Something failed while assembling Today',
      contract: null,
      issues: [],
      retryable: true,
      retry_after_seconds: 30,
      debug_ref: 'trace:tr_0001',
      request_id: 'request:r_0005',
      occurred_at: NOW,
    },
  },

  // ── vendor-time amendments, 2026-08-05 ────────────────────────────────────
  // Each of these is a payload the LAB copy refuses and this copy accepts. They
  // are the discriminating half of the amendment proof: a counterexample alone
  // cannot tell a widened enum from an unchanged one, because a bad value is
  // refused either way. `test/amendments.test.ts` asserts the pairing.
  {
    id: 'goal.pipeline_inferred',
    contract: 'cedrus.goal',
    note: 'origin=cedrus_inferred is the live partition key for pipeline-captured intentions. The lab enum could not hold it.',
    value: {
      schema_version: 2,
      goal_id: 'goal:g_reach_out',
      member_id: MEMBER,
      stated_text: 'reach out to someone this week',
      lane: 'people',
      origin: 'cedrus_inferred',
      status: 'open',
      priority: null,
      created_at: '2026-08-03T09:00:00Z',
      updated_at: NOW,
    },
  },
  {
    id: 'goal.long_but_legal',
    contract: 'cedrus.goal',
    note: '250 characters: over the lab\'s 200-char cap, under the deployed 280. Legal in the product, so legal in the contract.',
    value: {
      schema_version: 2,
      goal_id: 'goal:g_long',
      member_id: MEMBER,
      stated_text: `get back into swimming properly, ${'not just once and then never again, '.repeat(6)}`.slice(0, 250),
      lane: 'body',
      origin: 'user_set',
      status: 'open',
      priority: null,
      created_at: '2026-08-03T09:05:00Z',
      updated_at: NOW,
    },
  },
  {
    id: 'goal.missed',
    contract: 'cedrus.goal',
    note: 'status=missed is in the deployed user_goals_status_check. The lab enum (active/paused/retired) has no value for it.',
    value: {
      schema_version: 2,
      goal_id: 'goal:g_missed',
      member_id: MEMBER,
      stated_text: 'run three times this week',
      lane: 'body',
      origin: 'user_set',
      status: 'missed',
      priority: null,
      created_at: '2026-07-28T09:00:00Z',
      updated_at: NOW,
    },
  },
  {
    id: 'card_outcome.not_today',
    contract: 'cedrus.card_outcome',
    note: '"Not today" defers the card. Distinguishable from "not this", which suppresses the strategy, because scope is its own field.',
    value: {
      schema_version: 2,
      outcome_id: 'outcome:o_0003',
      card_id: 'card:cd_0003',
      member_id: MEMBER,
      outcome: 'deferred',
      helped: null,
      rejection_reason: 'wrong_time',
      rejection_scope: 'today',
      source: 'tap',
      verified: false,
      recorded_at: '2026-08-07T18:00:00Z',
    },
  },
  {
    id: 'card_outcome.rejected_without_saying_why',
    contract: 'cedrus.card_outcome',
    note: 'A member who rejects without giving a reason produces `unspecified`, not a null. Null would also mean "never asked".',
    value: {
      schema_version: 2,
      outcome_id: 'outcome:o_0004',
      card_id: 'card:cd_0004',
      member_id: MEMBER,
      outcome: 'did_not',
      helped: null,
      rejection_reason: 'unspecified',
      rejection_scope: 'this_action',
      source: 'sms',
      verified: false,
      recorded_at: '2026-08-07T19:00:00Z',
    },
  },
  {
    id: 'connection_authorization.disconnected_by_member',
    contract: 'cedrus.connection_authorization',
    note: 'The member turned it off. Not the same event as the provider revoking a token, and recorded as its own status.',
    value: {
      schema_version: 2,
      connection_id: 'conn:cn_0002',
      member_id: MEMBER,
      provider: 'google_calendar',
      scopes: ['calendar.freebusy.read'],
      purpose: {
        code: 'place_suggestions_in_open_time',
        statement: 'Place suggestions in time that is actually open on your calendar.',
      },
      named_outcome: {
        code: 'suggestions_land_in_time_you_actually_have',
        statement: 'Suggestions land in time you actually have, instead of on top of a meeting.',
      },
      disclosure: {
        reads: 'When you are busy and when you are free.',
        does_not_read: 'Event names, descriptions, locations, guests, or anything in Gmail.',
        will_do: 'Place suggestions in time that is actually open.',
        does_not_do: 'Cedrus does not create or change events.',
      },
      consent_ref: 'consent:c_0004',
      status: 'disconnected',
      authorized_at: '2026-08-04T15:00:00Z',
      last_sync_at: null,
      revoked_at: null,
      token_storage: 'server_only',
      revocable: true,
      writes_to_provider: false,
      state_validated: true,
    },
  },
  {
    id: 'agent_request.record_what_happened',
    contract: 'cedrus.agent_request',
    note: 'A job from the current §6.4 list. The lab enum, built against the pre-reboot list, has no value for it.',
    value: {
      schema_version: 1,
      request_id: 'request:r_0006',
      member_id: MEMBER,
      channel: 'sms',
      text: 'went for that swim this morning',
      received_at: '2026-08-05T13:00:00Z',
      in_scope: true,
      scope_job: 'record_what_happened',
      response_kind: 'answered',
      logged_as_request: true,
      fixed_register_trigger: 'none',
      voice_applied: true,
    },
  },
];

export const validExamplesFor = (contract: string): readonly ValidExample[] =>
  VALID_EXAMPLES.filter((e) => e.contract === contract);
